---
title: "8. ANOVA Extensions"
author: "jsg"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y %H:%M')`"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
    self_contained: true
---

Before doing this, review the **8. 2-way Anova** lecture set slides from 
https://sites.google.com/view/biostats/lessons/2-way-anovas-and-interactions and
the **8_Blocking_and_interactions.R** script in the lecture files folder of the
[CUNY-BioStats github repository](https://github.com/jsgosnell/CUNY-BioStats).
Make sure you are comfortable with null and alternative hypotheses and appropriate plots
for all examples.



Remember you should

* add code chunks by clicking the *Insert Chunk* button on the toolbar or by
pressing *Ctrl+Alt+I* to answer the questions!
* **knit** your file to produce a markdown version that you can see!
* save your work often 
  * **commit** it via git!
  * **push** updates to github
  
## Examples

## Practice

### 1

1. A survey was conducted to see if athletes and non-athletes deal with anger in
the same way.  Data is @

angry <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSaawG37o1ZUEs1B4keIJpZAY2c5tuljf29dWnzqQ0tHNCzfbz85AlWobYzBQ3nPPXJBLP-FWe4BNZB/pub?gid=1784556512&single=true&output=csv", stringsAsFactors = T)

and more information is at 

http://onlinestatbook.com/case_studies/angry_moods.html.

Focus on the following variables:

Sports
1 = athletes, 2 = non-athletes
Gender
1 = males, 2 = females
Expression (AE)
index of general anger expression: 
(Anger-Out) + (Anger-In) - (Control-Out) - (Control-In) + 48

Is there any evidence that gender or athlete status impact how anger is expressed?

### 2

2. A professor carried out a long-term study to see how various factors impacted
pulse rate before and after exercise.  Data can be found at 
http://www.statsci.org/data/oz/ms212.txt
With more info at 
http://www.statsci.org/data/oz/ms212.html.
Is there evidence that frequency of exercise
(Exercise column) and gender impact change in pulse rate for students who ran 
(Ran column = 1)?

### 3

3. (Continuing from question 2) I’m curious if the treatment (running vs not) even had an impact, and if so did it depend on gender. How would you test this?  

